import { Injectable } from '@angular/core';
import { MatDialog, MatDialogConfig } from '@angular/material';


const tooltips = {
  trackArtist: 'Email Confirmed!'
};


@Injectable()
export class TooltipService {

    trackTitle = 'EACH TRACK TITLE IN AN ALBUM MUST BE UNIQUE; THE EXCEPTION IS DIFFERENT VERSIONS OF THE SAME TRACK; SUCH AS CLEAN/EXPLICIT.';
    url = 'EACH TRACK MUST INCLUDE A UNIQUE URL LINK TO THE FILE.';
    sample = 'INDICATE IF THE TRACK CONTAINS A SAMPLE.';
    trackArtist = 'CLICK TO ADD AT LEAST ONE MAIN ARTIST.';
    trackArtistName = 'ARTIST FULL NAME AND PROPER SPELLING ARE REQUIRED IN THE MOST WIDELY KNOWN FORM.';
    trackArtistAliases = '';
    trackArtistIsni = '';
    featuredArtist = 'IF A TRACK CONTAINS ONE OR MORE FEATURED ARTISTS; EACH ARTIST MUST BE ADDED SEPARATELY.';
    featuredArtistIsni = '';
    isrc = 'A UNIQUE AND PERMANENT IDENTIFIER FOR A SPECIFIC RECORDING; INDEPENDENT OF THE FORMAT OR THE RIGHTS HOLDERS.';
    country = 'RECORDING LOCATION.';
    explicit = 'AN EXPLICIT TRACK MUST BE TAGGED AS EXPLICIT. A CLEAN VERSIONS OF EXPLICIT TRACKS MUST BE TAGGED AS CLEAN. TRACKS SHOULD ONLY BE FLAGGED CLEAN IF THERE IS AN EXPLICIT VERSION OF THE TRACK.';
    genre = 'THE FIRST GENRE MUST BE THE BEST DESCRIPTION FOR THE CONTENT. A SECOND GENRE IS NOT ALWAYS REQUIRED; BUT IT SHOULD BE USED WHEN APPLICABLE.';
    trackPline = 'THIS IS GENERALLY THE ENTITY ENTITLED TO ROYALTIES FOR THE TRACK.';
    trackNo = 'USED TO ORDER TRACKS WITHIN AN ALBUM.';
    trackVolumeNo = 'THE VOLUME NUMBER (DISC NUMBER) ON WHICH THE TRACK RESIDES.';
    releaseDate = 'THE ORIGINAL RELEASE DATE MUST BE THE EARLIEST DATE THAT THE ORIGINAL PRODUCT WAS FIRST RELEASED REGARDLESS OF THE RELEASING LABEL; OR FORMAT TYPE.';
    releaseYear = '';
    salesStartDate = 'THE SALES START DATE IS THE DATE WHEN CONTENT BECOMES AVAILABLE ON MUSE.';
    upcEan = 'SET OF NUMBERS THAT IDENTIFY A PACKAGED COLLECTION OF MUSIC';
    albumTitle = 'ALBUM TITLE MUST MATCH THE ORIGINAL TITLE UPON ITS INITIAL RELEASE.';
    partOfAlbum = 'ADD TOOLTIP';
    albumArtist = 'ADD TOOLTIP';
    albumProducer = 'ADD TOOLTIP';
    albumType = 'ADD TOOLTIP';
    albumPline = 'ADD TOOLTIP';
    albumCline = 'ADD TOOLTIP';
    masterLabel = 'ADD TOOLTIP';
    displayLabel = 'ADD TOOLTIP';



    // matTooltipShowDelay
    delay = '1000';

}
