export namespace Enums {
    export enum Genre {
        Rock,
        Pop,
        Metal,
        AcousticBlues,
        AdultAlternative,
        AdultContemporary,
        Africa,
        AfroBeat,
        AfroPop,
        Alternative,
        AlternativeCountry,
        AlternativeFolk,
        AlternativeRap,
        Alternativo,
        Ambient,
        AmericanTradRock,
        Americana,
        Anime,
        ArenaRock,
        Asian,
        Australia,
        AvantGarde,
        AvantGardeJazz,
        Axe,
        BaileFunk,
        BaladasYBoleros,
        Baroque,
        BigBand,
        Bluegrass,
        Blues,
        BluesRock,
        Bollywood,
        Bop,
        BossaNova,
        Brazilian,
        Breakbeat,
        BritishInvasion,
        Britpop,
        CPop,
        Cajun,
        CantopopHKPop,
        Caribbean,
        CCM,
        Celtic,
        CelticFolk,
        ChamberMusic,
        Chant,
        Chanukah,
        ChicagoBlues,
        ChildrensMusic,
        Chinese,
        ChineseAlt,
        ChineseClassical,
        ChineseFlute,
        ChineseHipHop,
        ChineseOpera,
        ChineseOrchestral,
        ChineseRegionalFolk,
        ChineseRock,
        ChineseStrings,
        Choral,
        Choro,
        ChristianGospel,
        ChristianMetal,
        ChristianPop,
        ChristianRap,
        ChristianRock,
        Christmas,
        ChristmasChildrens,
        ChristmasClassic,
        ChristmasClassical,
        ChristmasJazz,
        ChristmasModern,
        ChristmasPop,
        ChristmasRAndB,
        ChristmasReligious,
        ChristmasRock,
        ClassicBlues,
        ClassicChristian,
        Classical,
        ClassicalCrossover,
        CollegeRock,
        Comedy,
        ContemporaryBluegrass,
        ContemporaryBlues,
        ContemporaryCeltic,
        ContemporaryCountry,
        ContemporaryFolk,
        ContemporaryGospel,
        ContemporaryJazz,
        ContemporaryLatin,
        ContemporaryRAndB,
        ContemporarySingerSongwriter,
        Cool,
        Country,
        CountryBlues,
        CountryGospel,
        CrossoverJazz,
        Dance,
        Dancehall,
        Dangdut,
        DeathMetalBlackMetal,
        DeltaBlues,
        DevotionalAndSpiritual,
        Dini,
        DirtySouth,
        Disco,
        Disney,
        Dixieland,
        DooWop,
        Downtempo,
        DrinkingSongs,
        Dub,
        EarlyMusic,
        EastCoastRap,
        Easter,
        EasyListening,
        ElectricBlues,
        Electronic,
        Electronica,
        Enka,
        Environmental,
        Europe,
        Exercise,
        FitnessAndWorkout,
        FolkRock,
        ForeignCinema,
        Forro,
        France,
        FrenchPop,
        Frevo,
        Funk,
        Fusion,
        GangstaRap,
        Garage,
        GermanFolk,
        GermanPop,
        GlamRock,
        Gospel,
        GothRock,
        Grunge,
        HairMetal,
        Halk,
        Halloween,
        HardBop,
        HardRock,
        Hardcore,
        HardcoreRap,
        Hawaii,
        Healing,
        HeavyMetal,
        HighClassical,
        HipHopRap,
        HipHop,
        Holiday,
        HolidayOther,
        HonkyTonk,
        House,
        IDMExperimental,
        Impressionist,
        Indian,
        IndianClassical,
        IndianPop,
        IndieRock,
        IndoPop,
        IndonesianReligious,
        Industrial,
        Instrumental,
        JPop,
        JamBands,
        Japan,
        JapanesePop,
        Jazz,
        JungleDrumNbass,
        KPop,
        Karaoke,
        Kayokyoku,
        Klezmer,
        Korean,
        KoreanClassical,
        KoreanFolkPop,
        KoreanHipHop,
        KoreanIndie,
        KoreanRock,
        KoreanTradInstrumental,
        KoreanTradSong,
        KoreanTradTheater,
        Latin,
        LatinJazz,
        LatinRap,
        Lounge,
        Lullabies,
        MainstreamJazz,
        MalaysianPop,
        Mandopop,
        ManillaSound,
        Medieval,
        Meditation,
        MiddleEast,
        Minimalism,
        ModernComposition,
        Motown,
        MPB,
        Musicals,
        Nature,
        NeoSoul,
        NewAcoustic,
        NewAge,
        NewWave,
        NorthAmerica,
        Novelty,
        OldSchoolRap,
        Opera,
        Orchestral,
        OriginalPilipinoMusic,
        OriginalScore,
        OutlawCountry,
        Pagode,
        PinoyPop,
        Polka,
        PopLatino,
        PopRock,
        PraiseAndWorship,
        ProgRockArtRock,
        Psychedelic,
        Punk,
        QuietStorm,
        RAndBSoul,
        Ragtime,
        Raices,
        Rap,
        ReggaetonyHipHop,
        RegionalIndian,
        RegionalMexicano,
        Relaxation,
        Renaissance,
        RockAndRoll,
        RockLatino,
        Rockabilly,
        Romantic,
        RootsReggae,
        RootsRock,
        RussianChanson,
        SalsayTropical,
        Samba,
        Sanat,
        Sertanejo,
        SingAlong,
        SingerSongwriter,
        Ska,
        SmoothJazz,
        SoftRock,
        Soul,
        Soundtrack,
        SouthAfrica,
        SouthAmerica,
        SouthernGospel,
        SouthernRock,
        SpokenWord,
        Standards,
        StandupComedy,
        Stories,
        SufiAndGhazals,
        Surf,
        Swing,
        TaiPop,
        TaiwaneseFolk,
        Tamil,
        Techno,
        TeenPop,
        Telugu,
        TexMex,
        ThaiPop,
        Thanksgiving,
        TibetanNativeMusic,
        TradJazz,
        TraditionalBluegrass,
        TraditionalCeltic,
        TraditionalCountry,
        TraditionalFolk,
        TraditionalGospel,
        TraditionalPop,
        Trance,
        Travel,
        Trot,
        TVSoundtrack,
        UndergroundRap,
        UrbanCowboy,
        Vocal,
        VocalJazz,
        VocalPop,
        WeddingMusic,
        WestCoastRap,
        World,
        Worldbeat,
        Zydeco,
        Default
    }

    export enum GenreString {
        Rock = 'Rock',
        Pop = 'Pop',
        Metal = 'Metal',
        AcousticBlues = 'Acoustic Blues',
        AdultAlternative = 'Adult Alternative',
        AdultContemporary = 'Adult Contemporary',
        Africa = 'Africa',
        AfroBeat = 'Afro-Beat',
        AfroPop = 'Afro-Pop',
        Alternative = 'Alternative',
        AlternativeCountry = 'Alternative Country',
        AlternativeFolk = 'Alternative Folk',
        AlternativeRap = 'Alternative Rap',
        Alternativo = 'Alternativo',
        Ambient = 'Ambient',
        AmericanTradRock = 'American Trad Rock',
        Americana = 'Americana',
        Anime = 'Anime',
        ArenaRock = 'Arena Rock',
        Asian = 'Asian',
        Australia = 'Australia',
        AvantGarde = 'Avant-Garde',
        AvantGardeJazz = 'Avant-Garde Jazz',
        Axe = 'Axé',
        BaileFunk = 'Baile Funk',
        BaladasYBoleros = 'Baladas y Boleros',
        Baroque = 'Baroque',
        BigBand = 'Big Band',
        Bluegrass = 'Bluegrass',
        Blues = 'Blues',
        BluesRock = 'Blues-Rock',
        Bollywood = 'Bollywood',
        Bop = 'Bop',
        BossaNova = 'Bossa Nova',
        Brazilian = 'Brazilian',
        Breakbeat = 'Breakbeat',
        BritishInvasion = 'British Invasion',
        Britpop = 'Britpop',
        CPop = 'C-Pop',
        Cajun = 'Cajun',
        CantopopHKPop = 'Cantopop/HK-Pop',
        Caribbean = 'Caribbean',
        CCM = 'CCM',
        Celtic = 'Celtic',
        CelticFolk = 'Celtic Folk',
        ChamberMusic = 'Chamber Music',
        Chant = 'Chant',
        Chanukah = 'Chanukah',
        ChicagoBlues = 'Chicago Blues',
        ChildrensMusic = 'Children\'s Music',
        Chinese = 'Chinese',
        ChineseAlt = 'Chinese Alt',
        ChineseClassical = 'Chinese Classical',
        ChineseFlute = 'Chinese Flute',
        ChineseHipHop = 'Chinese Hip-Hop',
        ChineseOpera = 'Chinese Opera',
        ChineseOrchestral = 'Chinese Orchestral',
        ChineseRegionalFolk = 'Chinese Regional Folk',
        ChineseRock = 'Chinese Rock',
        ChineseStrings = 'Chinese Strings',
        Choral = 'Choral',
        Choro = 'Choro',
        ChristianGospel = 'Christian Gospel',
        ChristianMetal = 'Christian Metal',
        ChristianPop = 'Christian Pop',
        ChristianRap = 'Christian Rap',
        ChristianRock = 'Christian Rock',
        Christmas = 'Christmas',
        ChristmasChildrens = 'Christmas: Children\'s',
        ChristmasClassic = 'Christmas: Classic',
        ChristmasClassical = 'Christmas: Classical',
        ChristmasJazz = 'Christmas: Jazz',
        ChristmasModern = 'Christmas: Modern',
        ChristmasPop = 'Christmas: Pop',
        ChristmasRAndB = 'Christmas: R&B',
        ChristmasReligious = 'Christmas: Religious',
        ChristmasRock = 'Christmas: Rock',
        ClassicBlues = 'Classic Blues',
        ClassicChristian = 'Classic Christian',
        Classical = 'Classical',
        ClassicalCrossover = 'Classical Crossover',
        CollegeRock = 'College Rock',
        Comedy = 'Comedy',
        ContemporaryBluegrass = 'Contemporary Bluegrass',
        ContemporaryBlues = 'Contemporary Blues',
        ContemporaryCeltic = 'Contemporary Celtic',
        ContemporaryCountry = 'Contemporary Country',
        ContemporaryFolk = 'Contemporary Folk',
        ContemporaryGospel = 'Contemporary Gospel',
        ContemporaryJazz = 'Contemporary Jazz',
        ContemporaryLatin = 'Contemporary Latin',
        ContemporaryRAndB = 'Contemporary R&B',
        ContemporarySingerSongwriter = 'Contemporary Singer/Songwriter',
        Cool = 'Cool',
        Country = 'Country',
        CountryBlues = 'Country Blues',
        CountryGospel = 'Country Gospel',
        CrossoverJazz = 'Crossover Jazz',
        Dance = 'Dance',
        Dancehall = 'Dancehall',
        Dangdut = 'Dangdut',
        DeathMetalBlackMetal = 'Death Metal/Black Metal',
        DeltaBlues = 'Delta Blues',
        DevotionalAndSpiritual = 'Devotional & Spiritual',
        Dini = 'Dini',
        DirtySouth = 'Dirty South',
        Disco = 'Disco',
        Disney = 'Disney',
        Dixieland = 'Dixieland',
        DooWop = 'Doo Wop',
        Downtempo = 'Downtempo',
        DrinkingSongs = 'Drinking Songs',
        Dub = 'Dub',
        EarlyMusic = 'Early Music',
        EastCoastRap = 'East Coast Rap',
        Easter = 'Easter',
        EasyListening = 'Easy Listening',
        ElectricBlues = 'Electric Blues',
        Electronic = 'Electronic',
        Electronica = 'Electronica',
        Enka = 'Enka',
        Environmental = 'Environmental',
        Europe = 'Europe',
        Exercise = 'Exercise',
        FitnessAndWorkout = 'Fitness & Workout',
        FolkRock = 'Folk-Rock',
        ForeignCinema = 'Foreign Cinema',
        Forro = 'Forró',
        France = 'France',
        FrenchPop = 'French Pop',
        Frevo = 'Frevo',
        Funk = 'Funk',
        Fusion = 'Fusion',
        GangstaRap = 'Gangsta Rap',
        Garage = 'Garage',
        GermanFolk = 'German Folk',
        GermanPop = 'German Pop',
        GlamRock = 'Glam Rock',
        Gospel = 'Gospel',
        GothRock = 'Goth Rock',
        Grunge = 'Grunge',
        HairMetal = 'Hair Metal',
        Halk = 'Halk',
        Halloween = 'Halloween',
        HardBop = 'Hard Bop',
        HardRock = 'Hard Rock',
        Hardcore = 'Hardcore',
        HardcoreRap = 'Hardcore Rap',
        Hawaii = 'Hawaii',
        Healing = 'Healing',
        HeavyMetal = 'Heavy Metal',
        HighClassical = 'High Classical',
        HipHopRap = 'Hip Hop/Rap',
        HipHop = 'Hip-Hop',
        Holiday = 'Holiday',
        HolidayOther = 'Holiday: Other',
        HonkyTonk = 'Honky Tonk',
        House = 'House',
        IDMExperimental = 'IDM/Experimental',
        Impressionist = 'Impressionist',
        Indian = 'Indian',
        IndianClassical = 'Indian Classical',
        IndianPop = 'Indian Pop',
        IndieRock = 'Indie Rock',
        IndoPop = 'Indo Pop',
        IndonesianReligious = 'Indonesian Religious',
        Industrial = 'Industrial',
        Instrumental = 'Instrumental',
        JPop = 'J-Pop',
        JamBands = 'Jam Bands',
        Japan = 'Japan',
        JapanesePop = 'Japanese Pop',
        Jazz = 'Jazz',
        JungleDrumNbass = 'Jungle/Drum\'n\'bass',
        KPop = 'K-Pop',
        Karaoke = 'Karaoke',
        Kayokyoku = 'Kayokyoku',
        Klezmer = 'Klezmer',
        Korean = 'Korean',
        KoreanClassical = 'Korean Classical',
        KoreanFolkPop = 'Korean Folk-Pop',
        KoreanHipHop = 'Korean Hip-Hop',
        KoreanIndie = 'Korean Indie',
        KoreanRock = 'Korean Rock',
        KoreanTradInstrumental = 'Korean Trad Instrumental',
        KoreanTradSong = 'Korean Trad Song',
        KoreanTradTheater = 'Korean Trad Theater',
        Latin = 'Latin',
        LatinJazz = 'Latin Jazz',
        LatinRap = 'Latin Rap',
        Lounge = 'Lounge',
        Lullabies = 'Lullabies',
        MainstreamJazz = 'Mainstream Jazz',
        MalaysianPop = 'Malaysian Pop',
        Mandopop = 'Mandopop',
        ManillaSound = 'Manilla Sound',
        Medieval = 'Medieval',
        Meditation = 'Meditation',
        MiddleEast = 'Middle East',
        Minimalism = 'Minimalism',
        ModernComposition = 'Modern Composition',
        Motown = 'Motown',
        MPB = 'MPB',
        Musicals = 'Musicals',
        Nature = 'Nature',
        NeoSoul = 'Neo-Soul',
        NewAcoustic = 'New Acoustic',
        NewAge = 'New Age',
        NewWave = 'New Wave',
        NorthAmerica = 'North America',
        Novelty = 'Novelty',
        OldSchoolRap = 'Old School Rap',
        Opera = 'Opera',
        Orchestral = 'Orchestral',
        OriginalPilipinoMusic = 'Original Pilipino Music',
        OriginalScore = 'Original Score',
        OutlawCountry = 'Outlaw Country',
        Pagode = 'Pagode',
        PinoyPop = 'Pinoy Pop',
        Polka = 'Polka',  
        PopLatino = 'Pop Latino',
        PopRock = 'Pop/Rock',
        PraiseAndWorship = 'Praise & Worship',
        ProgRockArtRock = 'Prog-Rock/Art Rock',
        Psychedelic = 'Psychedelic',
        Punk = 'Punk',
        QuietStorm = 'Quiet Storm',
        RAndBSoul = 'R&B/Soul',
        Ragtime = 'Ragtime',
        Raices = 'Raices',
        Rap = 'Rap',
        ReggaetonyHipHop = 'Reggaeton y Hip-Hop',
        RegionalIndian = 'Regional Indian',
        RegionalMexicano = 'Regional Mexicano',
        Relaxation = 'Relaxation',
        Renaissance = 'Renaissance',
        RockAndRoll = 'Rock & Roll',
        RockLatino = 'Rock Latino',
        Rockabilly = 'Rockabilly',
        Romantic = 'Romantic',
        RootsReggae = 'Roots Reggae',
        RootsRock = 'Roots Rock',
        RussianChanson = 'Russian Chanson',
        SalsayTropical = 'Salsa y Tropical',
        Samba = 'Samba',
        Sanat = 'Sanat',
        Sertanejo = 'Sertanejo',
        SingAlong = 'Sing-Along',
        SingerSongwriter = 'Singer/Songwriter',
        Ska = 'Ska',
        SmoothJazz = 'Smooth Jazz',
        SoftRock = 'Soft Rock',
        Soul = 'Soul',
        Soundtrack = 'Soundtrack',
        SouthAfrica = 'South Africa',
        SouthAmerica = 'South America',
        SouthernGospel = 'Southern Gospel',
        SouthernRock = 'Southern Rock',
        SpokenWord = 'Spoken Word',
        Standards = 'Standards',
        StandupComedy = 'Standup Comedy',
        Stories = 'Stories',
        SufiAndGhazals = 'Sufi and Ghazals',
        Surf = 'Surf',
        Swing = 'Swing',
        TaiPop = 'Tai-Pop',
        TaiwaneseFolk = 'Taiwanese Folk',
        Tamil = 'Tamil',
        Techno = 'Techno',
        TeenPop = 'Teen Pop',
        Telugu = 'Telugu',
        TexMex = 'Tex-Mex',
        ThaiPop = 'Thai Pop',
        Thanksgiving = 'Thanksgiving',
        TibetanNativeMusic = 'Tibetan Native Music',
        TradJazz = 'Trad Jazz',
        TraditionalBluegrass = 'Traditional Bluegrass',
        TraditionalCeltic = 'Traditional Celtic',
        TraditionalCountry = 'Traditional Country',
        TraditionalFolk = 'Traditional Folk',
        TraditionalGospel = 'Traditional Gospel',
        TraditionalPop = 'Traditional Pop',
        Trance = 'Trance',
        Travel = 'Travel',
        Trot = 'Trot',
        TVSoundtrack = 'TV Soundtrack',
        UndergroundRap = 'Underground Rap',
        UrbanCowboy = 'Urban Cowboy',
        Vocal = 'Vocal',
        VocalJazz = 'Vocal Jazz',
        VocalPop = 'Vocal Pop',
        WeddingMusic = 'Wedding Music',
        WestCoastRap = 'West Coast Rap',
        World = 'World',
        Worldbeat = 'Worldbeat',
        Zydeco = 'Zydeco',
        Default = ''
    }

    export enum Countries {
        UnitedStates = 'United States',
        Canada = 'Canada',
        Afghanistan = 'Afghanistan',
        AfricanRepublic = 'African Republic',
        Albania = 'Albania',
        Algeria = 'Algeria',
        Andorra = 'Andorra',
        Angola = 'Angola',
        AntiguaandBarbuda = 'Antigua and Barbuda',
        Argentina = 'Argentina',
        Armenia = 'Armenia',
        Australia = 'Australia',
        Austria = 'Austria',
        Azerbaijan = 'Azerbaijan',
        Bahamas = 'Bahamas',
        Bahrain = 'Bahrain',
        Bangladesh = 'Bangladesh',
        Barbados = 'Barbados',
        Barbuda = 'Barbuda',
        Belarus = 'Belarus',
        Belgium = 'Belgium',
        Belize = 'Belize',
        Benin = 'Benin',
        Bhutan = 'Bhutan',
        Bolivia = 'Bolivia',
        BosniaandHerzegovina = 'Bosnia and Herzegovina',
        Botswana = 'Botswana',
        Brazil = 'Brazil',
        Brunei = 'Brunei',
        Bulgaria = 'Bulgaria',
        BurkinaFaso = 'Burkina Faso',
        Burma = 'Burma',
        Burundi = 'Burundi',
        CaboVerde = 'Cabo Verde',
        Cambodia = 'Cambodia',
        Cameroon = 'Cameroon',
        Central = 'Central',
        Chad = 'Chad',
        Chile = 'Chile',
        China = 'China',
        Colombia = 'Colombia',
        Comoros = 'Comoros',
        CongoBrazzaville = 'Congo (Brazzaville)',
        CongoKinshasa = 'Congo (Kinshasa)',
        CostaRica = 'Costa Rica',
        Côted = 'Côte d',
        Ivoire = 'Ivoire',
        Croatia = 'Croatia',
        Cuba = 'Cuba',
        Cyprus = 'Cyprus',
        Czechia = 'Czechia',
        Denmark = 'Denmark',
        Djibouti = 'Djibouti',
        Dominica = 'Dominica',
        DominicanRepublic = 'Dominican Republic',
        Ecuador = 'Ecuador',
        Egypt = 'Egypt',
        ElSalvador = 'El Salvador',
        EquatorialGuinea = 'Equatorial Guinea',
        Eritrea = 'Eritrea',
        Estonia = 'Estonia',
        Ethiopia = 'Ethiopia',
        Fiji = 'Fiji',
        Finland = 'Finland',
        France = 'France',
        Gabon = 'Gabon',
        Gambia = 'Gambia',
        Georgia = 'Georgia',
        Germany = 'Germany',
        Ghana = 'Ghana',
        Greece = 'Greece',
        Grenada = 'Grenada',
        Guatemala = 'Guatemala',
        Guinea = 'Guinea',
        GuineaBissau = 'Guinea-Bissau',
        Guyana = 'Guyana',
        Haiti = 'Haiti',
        HolySee = 'Holy See',
        Honduras = 'Honduras',
        Hungary = 'Hungary',
        Iceland = 'Iceland',
        India = 'India',
        Indonesia = 'Indonesia',
        Iran = 'Iran',
        Iraq = 'Iraq',
        Ireland = 'Ireland',
        Israel = 'Israel',
        Italy = 'Italy',
        Jamaica = 'Jamaica',
        Japan = 'Japan',
        Jordan = 'Jordan',
        Kazakhstan = 'Kazakhstan',
        Kenya = 'Kenya',
        Kiribati = 'Kiribati',
        Kosovo = 'Kosovo',
        Kuwait = 'Kuwait',
        Kyrgyzstan = 'Kyrgyzstan',
        Laos = 'Laos',
        Latvia = 'Latvia',
        Lebanon = 'Lebanon',
        Lesotho = 'Lesotho',
        Liberia = 'Liberia',
        Libya = 'Libya',
        Liechtenstein = 'Liechtenstein',
        Lithuania = 'Lithuania',
        Luxembourg = 'Luxembourg',
        Macedonia = 'Macedonia',
        Madagascar = 'Madagascar',
        Malawi = 'Malawi',
        Malaysia = 'Malaysia',
        Maldives = 'Maldives',
        Mali = 'Mali',
        Malta = 'Malta',
        MarshallIslands = 'Marshall Islands',
        Mauritania = 'Mauritania',
        Mauritius = 'Mauritius',
        Mexico = 'Mexico',
        Micronesia = 'Micronesia',
        Moldova = 'Moldova',
        Monaco = 'Monaco',
        Mongolia = 'Mongolia',
        Montenegro = 'Montenegro',
        Morocco = 'Morocco',
        Mozambique = 'Mozambique',
        Namibia = 'Namibia',
        Nauru = 'Nauru',
        Nepal = 'Nepal',
        Netherlands = 'Netherlands',
        NewZealand = 'New Zealand',
        Nicaragua = 'Nicaragua',
        Niger = 'Niger',
        Nigeria = 'Nigeria',
        NorthKorea = 'North Korea',
        Norway = 'Norway',
        Oman = 'Oman',
        Pakistan = 'Pakistan',
        Palau = 'Palau',
        Panama = 'Panama',
        PapuaNewGuinea = 'Papua New Guinea',
        Paraguay = 'Paraguay',
        Peru = 'Peru',
        Philippines = 'Philippines',
        Poland = 'Poland',
        Portugal = 'Portugal',
        Qatar = 'Qatar',
        Romania = 'Romania',
        Russia = 'Russia',
        Rwanda = 'Rwanda',
        SaintKittsandNevis = 'Saint Kitts and Nevis',
        SaintLucia = 'Saint Lucia',
        SaintVincentandtheGrenadines = 'Saint Vincent and the Grenadines',
        Samoa = 'Samoa',
        SanMarino = 'San Marino',
        SaoTomeandPrincipe = 'Sao Tome and Principe',
        SaudiArabia = 'Saudi Arabia',
        Senegal = 'Senegal',
        Serbia = 'Serbia',
        Seychelles = 'Seychelles',
        SierraLeone = 'Sierra Leone',
        Singapore = 'Singapore',
        Slovakia = 'Slovakia',
        Slovenia = 'Slovenia',
        SolomonIslands = 'Solomon Islands',
        Somalia = 'Somalia',
        SouthAfrica = 'South Africa',
        SouthKorea = 'South Korea',
        SouthSudan = 'South Sudan',
        Spain = 'Spain',
        SriLanka = 'Sri Lanka',
        Sudan = 'Sudan',
        Suriname = 'Suriname',
        Swaziland = 'Swaziland',
        Sweden = 'Sweden',
        Switzerland = 'Switzerland',
        Syria = 'Syria',
        Taiwan = 'Taiwan',
        Tajikistan = 'Tajikistan',
        Tanzania = 'Tanzania',
        Thailand = 'Thailand',
        TimorLeste = 'Timor-Leste',
        Togo = 'Togo',
        Tonga = 'Tonga',
        TrinidadandTobago = 'Trinidad and Tobago',
        Tunisia = 'Tunisia',
        Turkey = 'Turkey',
        Turkmenistan = 'Turkmenistan',
        Tuvalu = 'Tuvalu',
        Uganda = 'Uganda',
        Ukraine = 'Ukraine',
        UnitedArabEmirates = 'United Arab Emirates',
        UnitedKingdom = 'United Kingdom',
        Uruguay = 'Uruguay',
        Uzbekistan = 'Uzbekistan',
        Vanuatu = 'Vanuatu',
        Venezuela = 'Venezuela',
        Vietnam = 'Vietnam',
        Yemen = 'Yemen',
        Zambia = 'Zambia',
        Zimbabwe = 'Zimbabwe',
        Default = ''
    }

    export enum AlbumType {
        AlbumLive = 'Album (Live)',
        AlbumCompilation = 'Album (Compilation)',
        AlbumStudio = 'Album (Studio)',
        EP = 'EP',
        MusicVideo = 'Music Video',
        Ringtone = 'Ringtone',
        Single = 'Single',
        Default = ''
    }

    export enum Explicit {
        Yes,
        No,
        Clean,
    }

    export enum Pros {
        ACEMLA = 'ACEMLA',
        ACUM = 'ACUM',
        AEPI = 'AEPI',
        AGADU = 'AGADU',
        AKM = 'AKM',
        APDAYC = 'APDAYC',
        APRA = 'APRA',
        ARTISJUS = 'ARTISJUS',
        ASCAP = 'ASCAP',
        BMI = 'BMI',
        BUMA = 'BUMA',
        CASH = 'CASH',
        COMPASS = 'COMPASS',
        COTT = 'COTT',
        EAU = 'EAU',
        ECAD = 'ECAD',
        FILSCAP = 'FILSCAP',
        GEA = 'GEA',
        GEMA = 'GEMA',
        HDS = 'HDS',
        IMA = 'IMA',
        IPRS = 'IPRS',
        JASRAC = 'JASRAC',
        KODA = 'KODA',
        KOMCA = 'KOMCA',
        KOSCAP = 'KOSCAP',
        LATGA_A = 'LATGA-A',
        MACP = 'MACP',
        MCT = 'MCT',
        MRCSN = 'MRCSN',
        MUST = 'MUST',
        OSA = 'OSA',
        PPCA = 'PPCA',
        PRS_PPL = 'PRS, PPL',
        RAO = 'RAO',
        SABAM = 'SABAM',
        SACEM = 'SACEM',
        SACM = 'SACM',
        SACVEN = 'SACVEN',
        SADAIC = 'SADAIC',
        SAMRO = 'SAMRO',
        SAS = 'SAS',
        SAYCO_ACINPRO = 'SAYCO/ACINPRO',
        SCD = 'SCD',
        SENAPI = 'SENAPI',
        SGAE = 'SGAE',
        SIAE = 'SIAE',
        SOKOJ = 'SOKOJ',
        SOZA = 'SOZA',
        SPAC = 'SPAC',
        SPACEM = 'SPACEM',
        STIM = 'STIM',
        SUISA = 'SUISA',
        TEOSTO = 'TEOSTO',
        TONO = 'TONO',
        UACRR = 'UACRR',
        UCMR = 'UCMR',
        ZAIKS = 'ZAIKS',
        Default = ''
    }

    export enum Samples {
        Yes,
        No,
        Default = ''
    }

    export enum WritersRole {
        Composer,
        Lyrics,
        music_lyrics,
        Arranger,
        Default = ''
    }
}
